parameters:
#    estina_generator.example.class: Estina\GeneratorBundle\Example

services:
#    estina_generator.example:
#        class: %estina_generator.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
